# Generated by Django 3.2 on 2021-09-28 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.BooleanField(default=False)),
                ('file', models.FileField(null=True, upload_to='')),
                ('wallet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.wallet')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.wallet')),
            ],
        ),
        migrations.CreateModel(
            name='Adviser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.BooleanField(default=False)),
                ('file', models.FileField(null=True, upload_to='')),
                ('wallet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.wallet')),
            ],
        ),
    ]
