# Generated by Django 3.2 on 2021-09-28 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(null=True, upload_to='')),
                ('status', models.CharField(choices=[('ns', 'not seen'), ('ap', 'approved'), ('unap', 'unapproved')], default='ns', max_length=5)),
            ],
        ),
        migrations.RemoveField(
            model_name='adviser',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='adviser',
            name='file',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='file',
        ),
        migrations.AddField(
            model_name='adviser',
            name='document',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='adviser', to='users.document'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='document',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='teacher', to='users.document'),
        ),
    ]
