# Generated by Django 3.2 on 2021-09-29 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210929_0106'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='reason',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(null=True, upload_to='documnts/'),
        ),
    ]
