# Generated by Django 3.2 on 2021-09-29 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lapi', '0005_auto_20210929_2039'),
        ('users', '0003_auto_20210929_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='adviser',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='advisers', to='lapi.category'),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
