# Generated by Django 3.2 on 2021-09-29 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lapi', '0005_auto_20210929_2039'),
        ('users', '0004_auto_20210929_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adviser',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='advisers', to='lapi.category'),
        ),
        migrations.AlterField(
            model_name='adviser',
            name='document',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='adviser', to='users.document'),
        ),
    ]
