# Generated by Django 3.2 on 2021-10-21 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210929_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='adviser',
            name='apprvoed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teacher',
            name='apprvoed',
            field=models.BooleanField(default=False),
        ),
    ]
