# Generated by Django 3.2 on 2021-10-25 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20211021_1656'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adviser',
            old_name='apprvoed',
            new_name='approved',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='apprvoed',
            new_name='approved',
        ),
    ]
