# Generated by Django 3.2 on 2021-10-09 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts_api', '0003_auto_20211009_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='seo',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='seo',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
