# Generated by Django 3.2 on 2021-10-09 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210929_2046'),
        ('posts_api', '0006_auto_20211009_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, to='users.Student'),
        ),
    ]
