# Generated by Django 3.2 on 2021-10-16 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts_api', '0007_alter_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcopy',
            name='delete_request',
            field=models.BooleanField(default=False),
        ),
    ]
