# Generated by Django 3.2 on 2021-11-16 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts_api', '0008_postcopy_delete_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcopy',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
