# Generated by Django 3.2 on 2021-09-28 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('price', models.PositiveBigIntegerField()),
                ('chapters', models.TextField(blank=True)),
                ('lessons', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('duration', models.PositiveBigIntegerField()),
                ('is_class', models.BooleanField(default=False)),
                ('approved', models.BooleanField(default=False)),
                ('change_approved', models.BooleanField(default=True)),
                ('likes', models.ManyToManyField(blank=True, related_name='like_courses', to='users.Student')),
                ('prequel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sequel', to='course.course')),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, null=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('question_file', models.FileField(blank=True, null=True, upload_to='')),
                ('answer_file', models.FileField(blank=True, null=True, upload_to='')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='course.course')),
            ],
        ),
        migrations.CreateModel(
            name='ClassFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('file', models.FileField(blank=True, upload_to='')),
                ('approved', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='course.course')),
            ],
            options={
                'ordering': ['course'],
            },
        ),
        migrations.CreateModel(
            name='AnswerFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitting_time', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(blank=True, upload_to='')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='course.exam')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answerfiles', to='users.student')),
            ],
        ),
    ]
