# Generated by Django 3.2 on 2021-10-02 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lapi', '0006_rename_tag_category_tags'),
        ('course', '0002_auto_20210928_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='courses', to='lapi.Tag'),
        ),
    ]
