# Generated by Django 3.2 on 2021-10-05 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lapi', '0006_rename_tag_category_tags'),
        ('users', '0005_auto_20210929_2046'),
        ('course', '0003_course_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seminar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('price', models.PositiveBigIntegerField()),
                ('chapters', models.TextField(blank=True)),
                ('lessons', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('approved', models.BooleanField(default=False)),
                ('duration', models.PositiveBigIntegerField()),
                ('capacity', models.PositiveSmallIntegerField()),
                ('starting_time', models.DateTimeField()),
                ('ending_time', models.DateTimeField()),
                ('place', models.CharField(blank=True, max_length=300)),
                ('class_times', models.TextField()),
                ('attrib', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seminars', to='lapi.attrib')),
                ('likes', models.ManyToManyField(blank=True, related_name='like_seminars', to='users.Student')),
                ('prequel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sequel', to='course.seminar')),
                ('students', models.ManyToManyField(blank=True, related_name='seminars', to='users.Student')),
                ('tags', models.ManyToManyField(blank=True, related_name='seminars', to='lapi.Tag')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='seminars', to='users.teacher')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='course',
            name='change_approved',
        ),
        migrations.RemoveField(
            model_name='course',
            name='is_class',
        ),
        migrations.AddField(
            model_name='course',
            name='days_after_exam',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.CreateModel(
            name='Ticket4Seminar',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False, unique=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.seminar')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student')),
            ],
        ),
    ]
