# Generated by Django 3.2 on 2021-10-09 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_auto_20211005_1724'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exam',
            options={'ordering': ['-start_time']},
        ),
        migrations.AddField(
            model_name='course',
            name='after_days_exam',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='picture',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='course',
            name='seo',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seminar',
            name='city',
            field=models.CharField(max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='seminar',
            name='picture',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='seminar',
            name='seo',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
