# Generated by Django 3.2 on 2021-10-10 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_auto_20211009_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seminar',
            name='starting_seminar',
            field=models.DateTimeField(null=True),
        ),
    ]
