# Generated by Django 3.2 on 2021-10-10 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_alter_seminar_starting_seminar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seminarcopy',
            name='starting_seminar',
            field=models.DateTimeField(),
        ),
    ]
