# Generated by Django 3.2 on 2021-10-16 17:41

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_alter_seminarcopy_starting_seminar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='after_days_exam',
        ),
        migrations.RemoveField(
            model_name='seminar',
            name='class_times',
        ),
        migrations.AddField(
            model_name='classfile',
            name='free',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='classfile',
            name='seo',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coursecopy',
            name='delete_request',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seminarcopy',
            name='delete_request',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticket4seminar',
            name='part_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ticket4seminar',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
        migrations.CreateModel(
            name='Times',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.TimeField(max_length=24)),
                ('end', models.TimeField(max_length=24)),
                ('day', models.CharField(choices=[('0', 'شنبه'), ('1', 'یک شنبه'), ('2', 'دو شنبه'), ('3', 'سه شنبه'), ('4', 'چهار شنبه'), ('5', 'پنج شنبه'), ('6', 'جمعه')], max_length=1)),
                ('seminar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_times', to='course.seminar')),
            ],
        ),
    ]
