# Generated by Django 3.2 on 2021-11-01 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0012_auto_20211021_1547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursecopy',
            name='after_days_exam',
        ),
        migrations.RemoveField(
            model_name='coursecopy',
            name='days_after_exam',
        ),
    ]
