# Generated by Django 3.2 on 2021-11-02 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20211025_1840'),
        ('course', '0014_auto_20211102_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='waiting_students',
            field=models.ManyToManyField(blank=True, related_name='waiting_courses', to='users.Student'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='like_seminars', to='users.Student'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='seminars', to='users.Student'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='waiting_students',
            field=models.ManyToManyField(blank=True, related_name='waiting_seminars', to='users.Student'),
        ),
    ]
