# Generated by Django 3.2 on 2021-09-28 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('lapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attrib',
            name='teachers',
            field=models.ManyToManyField(blank=True, related_name='attribs', to='users.Teacher'),
        ),
        migrations.AddField(
            model_name='category',
            name='advisers',
            field=models.ManyToManyField(related_name='categories', to='users.Adviser'),
        ),
    ]
