# Generated by Django 3.2 on 2021-09-28 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('lapi', '0002_auto_20210928_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='advisers',
            field=models.ManyToManyField(blank=True, related_name='categories', to='users.Adviser'),
        ),
    ]
