# Generated by Django 3.2 on 2021-09-29 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210929_1737'),
        ('lapi', '0003_alter_category_advisers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket4Adviser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bought_at', models.DateTimeField(auto_now_add=True)),
                ('adviser', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='users.adviser')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='tickets', to='users.student')),
            ],
        ),
    ]
