# Generated by Django 3.2 on 2021-10-09 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lapi', '0006_rename_tag_category_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='seo',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attrib',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attribs', to='lapi.category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subs', to='lapi.category'),
        ),
    ]
