# Generated by Django 3.2 on 2021-10-09 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lapi', '0007_auto_20211009_1334'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(upload_to='')),
                ('alt', models.CharField(max_length=300)),
                ('picture', models.ImageField(upload_to='')),
                ('seo', models.JSONField()),
            ],
        ),
    ]
