# Generated by Django 3.2 on 2021-10-09 16:36

import django.db.models.deletion
from django.db import migrations, models

import lapi.models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_auto_20211009_2006'),
        ('lapi', '0008_media'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='media',
            name='picture',
        ),
        migrations.AddField(
            model_name='media',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medias', to='lapi.category'),
        ),
        migrations.AddField(
            model_name='media',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medias', to='course.course'),
        ),
        migrations.AddField(
            model_name='media',
            name='file',
            field=models.FileField(null=True, upload_to='', validators=[lapi.models.PictureAndVideoValidator]),
        ),
        migrations.AddField(
            model_name='media',
            name='seminar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medias', to='course.seminar'),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
