# Generated by Django 3.2 on 2021-10-16 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lapi', '0010_auto_20211009_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Ticket4Teacher',
        ),
    ]
