# Generated by Django 3.2 on 2021-10-18 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lapi', '0011_auto_20211016_2111'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('address', models.TextField()),
                ('phonenums', models.JSONField(null=True)),
                ('other', models.JSONField(null=True)),
            ],
        ),
    ]
