# Generated by Django 3.2 on 2021-11-18 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lapi', '0013_auto_20211024_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
